version: '2'
services:
  qsf2-app:
    image: qsf2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://qsf2-postgresql:5432/qsf2
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  qsf2-postgresql:
    extends:
      file: postgresql.yml
      service: qsf2-postgresql
